### ISSUE TITLE
How to run saskiaClone092617.pyde in Python 3.7.2?

### ISSUE THREAD

**Issue by Huaweidev** [hackingmath/WaveOfCubes#1]
How to run saskiaClone092617.pyde in Python 3.7.2?
Do i need install some lib/scripts?
Could you show the one-by-one steps into readme.md?

**Comment by hackingmath** [comment]
Hi, Jeff,

Thanks for the message. Yes, you have to download and install Processing to
run .pyde files. Here's the link to download/install:

https://processing.org/download/

The default mode is Java. To run .pyde files, you have to install the
Python mode by clicking "Java" in the interface and selecting the Python
mode. You only have to install the Python mode once and then it'll be
available in the drop down menu. Here's the screenshot from my book:
[image: image.png]
Hope this helps!

Peter Farrell

**Comment by Huaweidev** [comment]
Hi Peter,
It works, cool.
![pic_0123214056](https://user-images.githubusercontent.com/10258421/51610426-ba510b00-1f57-11e9-83df-2a6fd8967970.jpg)

**Comment by hackingmath** [comment]
Great! Happy it worked for you.
